### ISSUE TITLE
Code Coverage plugin Removes Plugin Cache directory

### ISSUE THREAD

**Issue by senorbum** [beckje01/grails-code-coverage#8]
I've recently added the Grails Code-Coverage plugin to my project. The coverage tools themselves work great. The issue I am facing is that every single time I run coverage, either on a single test or on the entire suite, my dependencies run into issues. I receive an error of The container 'Grails Dependencies' references non existing library 'C:\Users\$myUser.grails\1.3.6\projects\$myProject\plugin-classes'

The temporary solution is to refresh my dependencies. This works until the next time I run my tests with coverage. Looking at the mentioned directory, the folder it references definitely is deleted every time. Is there a config piece or something similar I could be missing?

Software Versions:

Grails 1.3.6
STS 2.9.2
Code-Coverage 1.2.5
Java 6

(Yes, this is a copy from my post at StackOverflow)

**Comment by beckje01** [comment]
Would you mind trying the plugin with version 1.2.6 and see if the problem still exists?

**Comment by senorbum** [comment]
Is there a better download site than the grails plugin directory?  Running grails installPlugin code-coverage 1.2.6 yields:   org.grails.plugins#code-coverage;1.2.6: not found

**Comment by beckje01** [comment]
So if you are getting that you are probably using the old plugin portal.

If you can upgrade grails 1.3.8 should fix that: http://jira.grails.org/browse/GRAILS-8970

If you can't upgrade there is a way to us the new portal I'll need a bit to track that down you are on a very old version of grails.

**Comment by senorbum** [comment]
I'll upgrade my local box and get back to you.

**Comment by senorbum** [comment]
I still have the same issue with grails 1.3.9 and code-coverage 1.2.6.  I've tried changing my plugin directory to ${project}/target, but I still get the same issue.

**Comment by beckje01** [comment]
Thanks I'll try with that this weekend, and see if I can reproduce as well.

**Comment by senorbum** [comment]
After upgrading my project to grails 2.2.4, I still get the same issue.  There must be some conflict with something on my machine causing this to happen.  I'm wondering if it is due to TFS locking files.  I will create a test project in the next few days to see if I can narrow down the issue.

**Comment by beckje01** [comment]
So any chance you could check with the latest version of coverage?

**Comment by beckje01** [comment]
No comment for a long time.
